---
title: "FormatMultiQC"
author: "Shelly Trigg"
date: "7/16/2020"
output: html_document
editor_options: 
  chunk_output_type: console
---

load libraries
```{r}
library(data.table)
library(gtools)
library(ggplot2)
library(knitr)
library(kableExtra)
```

read in data 
```{r}
#cutadapt stats
multiqc_a <- data.frame(fread("https://gannet.fish.washington.edu/metacarcinus/Pgenerosa/analyses/20200716/multiqc_data/multiqc_cutadapt.txt", header = TRUE, sep = "\t", stringsAsFactors = FALSE))

#bismark
multiqc_b <- data.frame(fread("https://gannet.fish.washington.edu/metacarcinus/Pgenerosa/analyses/20200716/multiqc_data/multiqc_bismark_alignment.txt", header = TRUE, sep = "\t", stringsAsFactors = FALSE))

#bismark meth-extract
multiqc_c <- data.frame(fread("https://gannet.fish.washington.edu/metacarcinus/Pgenerosa/analyses/20200716/multiqc_data/multiqc_bismark_methextract.txt", header = TRUE, sep = "\t", stringsAsFactors = FALSE))

#bismark dedup
multiqc_d <- data.frame(fread("https://gannet.fish.washington.edu/metacarcinus/Pgenerosa/analyses/20200716/multiqc_data/multiqc_bismark_dedup.txt", header = TRUE, sep = "\t", stringsAsFactors = FALSE))

#general stats
multiqc_g <- data.frame(fread("https://gannet.fish.washington.edu/metacarcinus/Pgenerosa/analyses/20200716/multiqc_data/multiqc_general_stats.txt", header = TRUE, sep = "\t", stringsAsFactors = FALSE))

#lambda alignment stats
#multiqc_l <- fread("https://gannet.fish.washington.edu/metacarcinus/FROGER_meth_compare/20200424/multiqc_data/multiqc_bismark_alignment.txt", header = TRUE, sep = "\t", stringsAsFactors = FALSE)

meta_data <- read.csv("RAnalysis/Data/Sample.Info.csv", stringsAsFactors = FALSE)




```


format meta data
```{r}
```


format multiqc sample names
```{r}
multiqc_a$Sample <- gsub("_S.*_L.*_R", "_R", multiqc_a$Sample)
multiqc_a$Sample <- gsub("_001", "", multiqc_a$Sample)
multiqc_b$Sample <- gsub("_.*", "", multiqc_b$Sample)
multiqc_c$Sample <- gsub("_.*", "", multiqc_c$Sample)
multiqc_d$Sample <- gsub("_.*", "", multiqc_d$Sample)
multiqc_g$Sample <- gsub("_S.*_L.*_R", "_R", multiqc_g$Sample)
multiqc_g$Sample <- gsub("_001", "", multiqc_g$Sample)
multiqc_g$Sample <- gsub("_val.*", "", multiqc_g$Sample)


```


format column names so merging won't produce duplicate colnames
```{r}
colnames(multiqc_b)[2] <- "uniq_aligned_reads"
colnames(multiqc_d)[2] <- "uniq_aligned_reads_no_discard"

```

#create table with trimming stats
```{r}
#subset the general stats table for the fastqc data
multiqc_f <- multiqc_g[,c(grep("Sample|FastQC",colnames(multiqc_g)))]
#remove rows with all NAs
multiqc_f <- multiqc_f[complete.cases(multiqc_f),]


#merge cutadapt and fastqc stats by Sample
trim_multiqc <- merge(multiqc_a,multiqc_f, by = "Sample")

#create read pair column
trim_multiqc$read_pair <- gsub(".*_R","R",trim_multiqc$Sample)

#remove read pair info from sample and rename sample column to Sample.ID
trim_multiqc$Sample.ID <- gsub("_R.*","",trim_multiqc$Sample)
#convert hyphens to underscores
trim_multiqc$Sample.ID <- gsub("-","_",trim_multiqc$Sample.ID)

#remove original sample column
trim_multiqc$Sample <- NULL

#merge with meta data
trim_multiqc <- merge(meta_data[,c("Sample.ID", "Tank","Initial.Treatment","Secondary.Treatment", "TimePoint")], trim_multiqc, by = "Sample.ID")

#move read pair column 
trim_multiqc <- trim_multiqc[,c(1:5,17,6:16)]

#remove extra text from colnames
colnames(trim_multiqc) <- gsub("FastQC_mqc\\.generalstats\\.","", colnames(trim_multiqc))

#order table by Sample.ID 
trim_multiqc <- trim_multiqc[mixedorder(trim_multiqc$Sample.ID),]

write.csv(trim_multiqc, "RAnalysis/Output/Raw_trimmed_data_descriptive_stats.csv", row.names = FALSE, quote = FALSE)

```

create a bismark table
```{r}
#merge dedup and meth extract data
multi_bismark <- merge(multiqc_d, multiqc_c, by = "Sample", all = TRUE)

#merge with bismark alignment report
#exclude meth calls from bismark alignments because better to include these from meth extract report
colnames(multiqc_b[,c(5:7,10:18,20:22)]) #print columns to exclude
multi_bismark <- merge(multiqc_b[,-c(5:7,10:18,20:22)], multi_bismark, by = "Sample", all = TRUE) #merge

#change column 1 to Sample.ID
colnames(multi_bismark)[1] <- "Sample.ID"

#convert hyphen to underscore
multi_bismark$Sample.ID <- gsub("-","_",multi_bismark$Sample.ID)

#merge with meta data
multi_bismark <- merge(meta_data[,c("Sample.ID", "Tank","Initial.Treatment","Secondary.Treatment", "TimePoint")],multi_bismark, by ="Sample.ID")

#order data by sample 
multi_bismark <- multi_bismark[mixedorder(as.character(multi_bismark$Sample.ID)),]

#write out alignments table
write.csv(multi_bismark,"RAnalysis/Output/Alignments_descriptive_stats.csv", row.names = FALSE, quote = FALSE)
```


